name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}
      - name: Install dev deps
        run: uv pip install -e .[dev]
      - name: Lint
        run: ruff check --output-format=github . && ruff format --check .
      - name: Run tests
        run: pytest
